spatialaudio/python-sounddevice

sounddevice.py

This wraps PortAudio's `Pa_IsFormatSupported()`.

Add check_input_settings() and check_output_settings()

---

sounddevice.py

See #30.
This doesn't work in Python 3.2, but nobody should use that anyway.

Return bytes in DeviceList.__repr__() for Python 2

---

sounddevice.py

This PR adds a top-level function `get_stream()` for use with the imperative-style API of `play()`, `rec()`, `playrec()`, and `stop()`. It allows end users to access the current state of playback and recording at the Stream level.
This PR effectively closes Issue #69.

Add `get_stream()` function for accessing the current Stream

---

sounddevice.py

Use 'replace' when encoding unicode device strings

---

sounddevice.py

fix for #1 
this commit makes sure that any streams started with play/rec/playrec
are closed before exiting to avoid segmentation faults from unreleased
PaStream objects
Added a similar try/finally to `StreamBase.__exit__` to make sure `with` always closes the stream properly.
Don't quote me on this but I'm pretty sure it's possible that a stream that has had `PaStopStream()` called on it can be started again without creating a new stream object so it may make sense to add a global `close` function to deallocate the stream corresponding to `_last_callback`.

fix issue #1

---

sounddevice.py

These 3 commits access PA's Core Audio API from pa_mac_core.h, and provide a "get_channel_name" function for querying names of individual device channels along with MacCoreSettings (for use with extra_settings) to expose additional Core Audio capabilities.  (See doc string in MacCoreSettings.)
My specific need for these extensions is that I have an RME Fireface UFX+ with a large number of input & output channels, and I didn't want to have to open many channels when only a couple are required.  The get_channel_name function lets me display obtain a set of user-friendly channel names from the underlying device driver (via PortAudio), which I may display to the operator / user.
I'm open for input to help get these changes incorporated into python-sounddevice.
Thank you,
David

Core Audio for interfaces with large #'s of channels

---

sounddevice.py

More ignore_errors arguments, call .stop() in stop()

---

sounddevice.py

I split this into three commits, because they have quite different implications.
I think setting the stream pointer to NULL (abf1f19839059453436738d8d2979d22772c101c) has no negative implications.
AFAICT, the error messages are the same as when using an invalid pointer after `close()`. But it might be safer on some systems (see mailing list link below).
The `.closed` property (8370db2cf4ff08a23119824f2cecd08ad15a1165) seems harmless, Python file objects tend to have such a thing, so it shouldn't be too uncommon.
The last commit (9af4e43a387e312e1c79e35eacb65b138b816c83) actually changes the behavior. Instead of throwing an exception, it now returns `active == False` on closed streams (without actually checking activeness).
I think that is logically justifiable, because a closed stream can …

close() sets the internal stream pointer to NULL

---

doc/conf.py
doc/fake__sounddevice.py

Switching to out-of-line ABI mode (#102) broke this.

DOC: fix fake import for API docs

---

doc/fake__sounddevice.py
src/sounddevice.py

This hopefully avoids the error described in https://github.com/bastibe/SoundFile/issues/207#issuecomment-343724483.

Raise a meaningful exception if PortAudio is not found

---

sounddevice.py

This should make the DLL from https://anaconda.org/conda-forge/portaudio usable for the `sounddevice` module.
Once https://anaconda.org/conda-forge/python-sounddevice is updated with the changes of this PR, it should be possible to use
conda install -c conda-forge python-sounddevice
... on Windows.
I guess on macOS it will still not work, because the `conda-forge` package isn't available for macOS.
It might work with this package though: https://anaconda.org/anaconda/portaudio.
But then the path to the dylib would have to be adapted for that.
I didn't try if anything like this works on Linux.

Try to load the PortAudio DLL from conda-forge

---

examples/plot_input.py

This avoids the message
MatplotlibDeprecationWarning:
Passing one of 'on', 'true', 'off', 'false' as a boolean is deprecated; use an actual boolean (True/False) instead.

plot_input example: 'off' -> False

---

sounddevice_build.py

This was the warning:
UserWarning: Global variable 'stderr' in cdef(): for consistency with C it should have a storage class specifier (usually 'extern')

Add "extern" to stderr to avoid CFFI warning

---

examples/play_long_file.py
examples/play_stream.py
sounddevice.py

Now that Python 2 support has been dropped, we can use `raise foo from bar`
More details about this change: https://blog.ram.rachum.com/post/621791438475296768/improving-python-exception-chaining-with

Fix exception causes all over the codebase

---

sounddevice.py

Hi,
This Pull Request adds the setters to CallbackFlags as we discusses in Issue #251.
I wasn't able to fathom out how to get PyTest working with sounddevice.  I had issues with the ffi import.  Had I been able to get it to work, I would have added tests to demonstrate the correct functionality.  As it stands, I just did the testing manually:
Finally, a comment about the instructions in the file "CONTRIBUTING".  Because I am working in a virtual environment, I found a variation of the pip install command worked best for me:
pip install -e .
Would you like that added to the documentation?
Cheers and thanks for all your work on sounddevice!
Matthew

Added setters to CallbackFlag's bits

---

sounddevice.py

See https://github.com/spatialaudio/python-sounddevice/issues/262#issuecomment-683347710.

Remove Python 2 compatibility with "basestring"

---

sounddevice_build.py

This function has been added in https://github.com/PortAudio/portaudio/pull/672 and hasn't yet been part of a PortAudio release.
For now, this can be used like this:
```python
import sounddevice as sd
sd._lib.PaWasapi_IsLoopback(7)
```
At a later point, we might want to add a more Pythonic interface.
See also #4 and #85.

Add PaWasapi_IsLoopback() to cdef

---

.github/workflows/python-versions.yml
doc/fake__sounddevice.py
examples/plot_input.py
examples/spectrogram.py
setup.py
sounddevice.py

Python 3.6 reached end of life.
In this PR I updated `setup.py`, CI workflow and ran `pyupgrade` on codebase:
```fish
for file in **/*.py; pyupgrade $file --py37-plus; end
```

Drop Python 3.6

---

sounddevice.py
sounddevice_build.py

I'm not quite sure yet if we should do this, this has to be tested thoroughly.
With a bit of luck, this might fix #90.
However, it might also have bad side effects ...

Redirect stderr with os.dup2() instead of CFFI calls

---

sounddevice.py

I guess the `__str__()` method of an exception should never raise an exception itself.
I saw this problem at https://stackoverflow.com/q/75713078/

Avoid exception in PortAudioError.__str__()

---

sounddevice.py
sounddevice_build.py

The default sample rate of my Wasapi output device is 48000. 
When I use it as the output device and play a 44100hz wav file, an error occured:
**`sounddevice.PortAudioError: Error opening RawOutputStream: Invalid sample rate [PaErrorCode -9997]`**
I read PortAudio source code and found that it has a flag `paWinWasapiAutoConvert = 64` that supports sample rate auto conversion.
If we pass the flag to PortAudio in shared mode, we can play a audio that sample rate is not equal to the Wasapi device's default.
I tested it and it worked.
The following code works with sounddevice 0.4.6 after setting
```
exSetting = sd.WasapiSettings()
exSetting._streaminfo.flags = paWinWasapiAutoConvert # set the flag 64, not needed if pull request is merged
```
```python
#!python3
import os
import sys
import …
```

support sample rate auto convert using PortAudio paWinWasapiAutoConvert flag when in share mode

---

sounddevice.py

This re-uses most of the text from https://portaudio.com/docs/v19-doxydocs/pa__win__wasapi_8h_source.html
See https://github.com/spatialaudio/python-sounddevice/pull/492#discussion_r1341941444.

DOC: update documentation for auto_convert

---

sounddevice.py

This is an alternative to #491.
It hopefully fixes #511.

ASIO: retry decoding device name after UnicodeDecodeError

---

doc/installation.rst

As described in #496, the ASIO-enabled DLLs cause problems.
With this PR, DLLs *without* ASIO will be provided by default.
The documentation describes how to get DLLs with ASIO for those who still need it.
Wheels for testing are available here: https://github.com/mgeier/python-sounddevice/actions/runs/9259857469/artifacts/1542028121

No ASIO by default

---

sounddevice.py

The index from enumerate won't match the actual device index if the list is filtered/reordered for whatever reason (i.e. to restrict to inputs/outputs or a specific API). This also means the default mark would be wrong. This fix uses the index in the dictionary instead.

Change DeviceList repr to use correct indices

---

doc/examples.rst

I inadvertently disabled it in #495.

DOC: re-enable syntax highlighting for included example code

---

setup.py
sounddevice.py

This PR adds the option to load an alternative PortAudio binary with ASIO support, enabled using an environ flag.
Additional PortAudio binaries compiled with ASIO will need to be maintained in the `_sounddevice_data` repository (e.g. named `libportaudio64bit-asio.dll`). They will then be bundled like default binary in the built package and can then be used by using the os.environ["SD_ENABLE_ASIO"] flag.
This PR is based on, and is the inverse of #498, since the default is now ASIO-disabled.
Minimal example:
```py
import os
os.environ["SD_ENABLE_ASIO"] = "1"
import sounddevice as sd
print(sd.query_hostapis())
```

Add an environ flag to load an ASIO PortAudio binary

---

.github/workflows/sounddevice-data.yml
doc/installation.rst

This adds documentation for #556.

DOC: describe the SD_ENABLE_ASIO environment variable

---

CONTRIBUTING.rst
doc/CONTRIBUTING.rst
doc/api/checking-hardware.rst
doc/api/convenience-functions.rst
doc/api/expert-mode.rst
doc/api/misc.rst
doc/api/platform-specific-settings.rst
doc/api/raw-streams.rst
doc/api/streams.rst
doc/conf.py
doc/contributing.rst
doc/examples.rst
doc/index.rst
doc/installation.rst
sounddevice.py

I restored the highlighting for code examples in #549, however I didn't realize that the code provided by `sphinx.ext.viewcode` wasn't highlighted either.
This now uses default (i.e. Python) highlighting again, but disables highlighting explicitly where I don't want it.

DOC: restore viewcode highlighting, disable unwanted highlighting

---

.github/workflows/publish.yml

This way, if somebody makes a PR that affects the build process (like e.g. #560), building the wheels is also tested (and they are available as artifacts to be inspected).

CI: build distribution also on pull request

---

sounddevice.py

Allow input/output parameter pairs in all constructors

---

doc/conf.py
sounddevice.py

Thanks to @timhoffm for reminding me of that option (https://github.com/sphinx-doc/sphinx/pull/12944#discussion_r1788952622)!

DOC: switch default_role from 'any' to 'py:obj'

---

sounddevice.py

... to avoid "incompatible override" warning from Pyright.

Add _InputStreamBase/_OutputStreamBase
