spatialaudio/python-sounddevice

doc/examples.rst
examples/spectrogram.py

Based on https://gist.github.com/maurisvh/df919538bcef391bc89f
@maurisvh I hope it's OK that I stole the idea and some code from you!

Add spectrogram example

---

sounddevice.py

... even if there are other (partial) matches.
Before this PR, an error was raised in this case.
Multiple exact matches (common on Windows) still raise an error.
Any objections?

Exact device string always selects the device

---

sounddevice.py

Try to send PortAudio output to /dev/null

---

sounddevice.py

Work-around to avoid channel duplication if mapping=[1]

---

sounddevice.py

Check for AttributeError when trying to silence stderr

---

doc/index.rst
sounddevice.py

WARNING: this is untested!
See #4.

Add extra_settings and AsioSettings

---

doc/index.rst
sounddevice.py

Add setting for WASAPI exclusive mode

---

sounddevice.py

atexit.unregister() removes all instances of the registered function,
not only one, therefore nested calls didn't work like they are supposed
to. See http://portaudio.com/docs/v19-doxydocs/portaudio_8h.html and
https://docs.python.org/3/library/atexit.html#atexit.unregister.
This commit fixes #47, which was the real reason for the change, since
atexit.unregister() doesn't even exist in Python 2.

Fix "atexit" handling

---

setup.py

Require at least CFFI version 1.0

---

sounddevice.py

People who want to create their own callback-based stream classes can directly inherit from `_StreamBase`, avoiding the unnecessary (and non-functional) `read()` and `write()` methods.
Also, if desired, they can quite easily implement a single stream class that (based on constructor arguments) supports only inputs, only outputs, or both inputs and outputs.

Simplify deriving from _StreamBase

---

sounddevice.py

Note that `kind` is now a non-optional argument.

Re-introduce kind='duplex' for _StreamBase

---

sounddevice.py

Remove __del__

---

sounddevice.py

First try 'utf-8' then 'mbcs' on MME and DS device names

---

sounddevice.py

Attach portaudio error codes to portaudio errors to allow for better error handling. This would allow users to handle specific portaudio and host api error codes. The `_check` function was also updated to use these new exceptions. The `from_errno` and `from_errinfo` are a convenience that I thought might make it easier for users to raise an exception with a default message. Hopefully this doesn't add too much complexity to the code.

adds error codes to PortAudioErrors and a new HostAPIError type

---

sounddevice.py

Added support for:
```
import sounddevice as sd
sd.query_devices("Scarlet")
sd.query_devices(u"Scarlet")
```

Added support for unicode strings on python 2.x

---

.gitmodules
setup.py
src/sounddevice.py

Warning: this doesn't work unless we add `_sounddevice_data/__init__.py`, see https://github.com/spatialaudio/python-sounddevice/issues/110#issuecomment-343727313.

Import _sounddevice_data for locating PortAudio

---

sounddevice.py

play() etc.: force a copy of "mapping"

---

sounddevice.py

Try to load PortAudio dylib from anaconda

---

doc/examples.rst
examples/asyncio_coroutines.py
examples/asyncio_generators.py

asyncio examples

---

sounddevice.py

Redirect stderr only during initialization

---

doc/installation.rst

DOC: Add information about ASIO support

---

doc/examples.rst
examples/play_sine.py

DOC: Add sine example

---

doc/api/index.rst
doc/api/misc.rst
sounddevice.py

DOC: Update module docstring after splitting API docs

---

README.rst

DOC: Mention OS support in README

---

doc/api/checking-hardware.rst
doc/api/convenience-functions.rst
doc/api/misc.rst
doc/api/module-defaults.rst
doc/api/platform-specific-settings.rst
doc/api/raw-streams.rst
doc/api/streams.rst
doc/conf.py
sounddevice.py

This is an "add-on" to #207.
@cool-RR What do you think about this?

DOC: Add autosummary to each API sub-page

---

doc/api/expert-mode.rst
doc/api/index.rst
doc/installation.rst
sounddevice.py

DOC: Add page about "expert mode"

---

sounddevice.py

Drop temporary buffers and CFFI objects when stream is finished

---

sounddevice.py

See #155.
Any further suggestions?

DOC: mention how to avoid under-/overflows

---

CONTRIBUTING.rst
doc/installation.rst

DOC: remove "--user" flag from installation instructions

---

doc/api/misc.rst
doc/conf.py
doc/requirements.txt

Rendered: https://python-sounddevice--284.org.readthedocs.build/en/284/

DOC: Switch to insipid theme

---

sounddevice.py

Hi,
I added a note to the documentation of a Stream's desired latency indicating that 'high' may not be sufficient to obtain stable audio.
In my commit history there's a revert.  Does this impact you in any way?  Or do my commits just get merged into one at your end?
Cheers,
Matthew

High latency doc

---

setup.py

Modern versions of pip should be able to deal with those shorter names.

Simplify wheel names

---

.github/workflows/sounddevice-data.yml

Update portaudio-binaries submodule to version 19.7.0

---

doc/installation.rst
sounddevice.py

Rendered: https://python-sounddevice--355.org.readthedocs.build/en/355/api/module-defaults.html

Documentation update

---

sounddevice.py

See https://stackoverflow.com/q/67374915/.

Show more meaningful error message if audio input has > 2 dimensions

---

doc/installation.rst

Rendered: https://python-sounddevice--357.org.readthedocs.build/en/357/installation.html

DOC: mention Miniconda

---

sounddevice.py

Fix dimension check in Stream.write()

---

examples/rec_gui.py

rec_gui example: check input instead of output

---

make_dist.sh

`setup.py` isn't cool enough anymore.

Update build script to use "build"

---

doc/installation.rst

The change from #414 has been reverted.

Fix Gohlke link (again)

---

sounddevice.py

Import NumPy in _StreamBase.__init__

---

sounddevice_build.py

Add PaWasapi_UpdateDeviceList to cdef

---

doc/installation.rst

Rendered: https://python-sounddevice--518.org.readthedocs.build/en/518/installation.html#custom-portaudio-library

DOC: Describe how to use a custom so/dylib/dll

---

sounddevice.py

This hopefully helps debugging issues like #553.

Improve the error message in _split()
